# Generated by Django 4.1.5 on 2023-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
