# Generated by Django 4.1.5 on 2023-02-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantor', '0002_user_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
